### ISSUE TITLE
OneDrive 学校账户认证失败

### ISSUE THREAD

**Issue by learningdog1** [sukechris/seanote#1]
sync notes，选择OneDrive作为云同步，登陆学生账户发生认证失败。
<img width="601" alt="image" src="https://github.com/sukechris/seanote/assets/110441496/e04ae86a-b2a7-4120-b689-acd4900ae773">

**Comment by sukechris** [comment]
@learningdog1  嗨，你好，Seanote 的 OneDrive 同步只支持个人账户，为了解决你的同步问题，你可以使用其他同步服务

- OneDrive for personal
- Dropbox
- WebDav

> 给了更好的同步体验，最好将 Seanote 升级到 v1.2.0+，https://seanote.app/downloads

这一点我在应用和文档中没有很好的说明，很抱歉给你造成困扰，为了补偿，如果你方便的话可以给 support@seanote.app 留个邮箱，送你一年的 Early Bird Pro 会员。
